[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_NPM_VERSION = "10"
CI = "false"